version: '0'

services:
  frontend:
    build: streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    command: streamlit run streamlit/app.py
  
  fastapi:
    build: fastapi
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: python app.py

volumes:
  app: