version: '3'
services:
  fastapi:
    build: ./fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    env_file:
      - .env

  streamlit:
    build: ./streamlit
    ports:
      - "8501:8501"
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_root_password}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
       - "3307:3306" 
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
