FROM python:3.12

WORKDIR /workspace/practice/fastapi

RUN pip install fastapi uvicorn

COPY . .
EXPOSE 8000

# Run app.py when the container launches
# CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
CMD ["python", "app.py"]